version: "2.4"
services: 
    member_service:
        build: 
            context: .
            target: gympair_member
        container_name: gympair_member
        ports: 
            - "9090:9090"
        links:
            - mysql:gympair_mysql
    mysql:
        build:
            context: .
            target: gympair_mysql
        container_name: gympair_mysql
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=ichat
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=henry
            - MYSQL_PASSWORD=123456