Server:
  RunMode: debug
  HttpPort: 9090
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogFilePath: /Users/henry/go/src/github.com/Henry19910227/gym-pair/storage/
  LogFileName: app
  LogFileExt: log
Database:
  DBType: mysql
  UserName: henry
  Password: aaaa8027
  Host: 127.0.0.1:8889
  DBName: ichat