Server:
  RunMode: debug
  HttpPort: 9090
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogFilePath: .
  LogFileName: app
  LogFileExt: log
  UploadSavePath: ./storege
  UploadImageAllowExt:
    - .jpg
    - .png
  UploadImageMaxSize: 1 #MB
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: gympair_mysql:3306
  DBName: ichat
JWT:
  Secret: henry
  Issuer: gympair
  Expire: 1 #hour