Server:
  RunMode: debug
  HttpPort: 9090
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogFilePath: .
  LogFileName: app
  LogFileExt: log
  UploadSavePath: ./storege
  UploadImageAllowExt:
    - .jpg
    - .png
  UploadImageMaxSize: 1 #MB
Database:
  DBType: mysql
  UserName: henry
  Password: aaaa8027
  Host: 127.0.0.1:8889
  DBName: ichat
JWT:
  Secret: henry
  Issuer: gympair
  Expire: 3600